name: Generate New Stable Signing Key

on:
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-latest

    steps:
      - name: Generate stable JKS
        run: |
          keytool -genkeypair \
            -v \
            -keystore newfashion-stable.jks \
            -storetype JKS \
            -storepass "NewFashion@2026" \
            -alias "newfashion" \
            -keypass "NewFashion@2026" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=New Fashion Tailoring, OU=App, O=New Fashion Tailoring, L=India, ST=Tamil Nadu, C=IN"

      - name: Verify JKS
        run: |
          keytool -list \
            -keystore newfashion-stable.jks \
            -storetype JKS \
            -storepass "NewFashion@2026" \
            -alias "newfashion"

      - name: Create Base64 Secret Value
        run: |
          base64 -w 0 newfashion-stable.jks > newfashion-stable-base64.txt

      - name: Show SHA-256
        run: |
          keytool -list -v \
            -keystore newfashion-stable.jks \
            -storetype JKS \
            -storepass "NewFashion@2026" \
            -alias "newfashion" | grep "SHA256:"

      - name: Upload signing files
        uses: actions/upload-artifact@v4
        with:
          name: New-Fashion-Stable-Signing-Key
          path: |
            newfashion-stable.jks
            newfashion-stable-base64.txt
