name: Generate Signing Key

on:
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore newfashion-release.jks \
            -storepass newfashion123 \
            -alias newfashion \
            -keypass newfashion123 \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=New Fashion Tailoring, OU=App, O=New Fashion Tailoring, L=India, ST=Tamil Nadu, C=IN"

      - name: Convert keystore to Base64
        run: |
          base64 -w 0 newfashion-release.jks > newfashion-keystore-base64.txt

      - name: Upload signing files
        uses: actions/upload-artifact@v4
        with:
          name: New-Fashion-Signing-Key
          path: |
            newfashion-release.jks
            newfashion-keystore-base64.txt
